### PR TITLE
[balancer-smart-pool] Add/balancer smart pool token score

### LINKED ISSUE #115: Balancer strategy not working for smart pools
### Expected behavior
Snapshot should recognize users with LP tokens of a smart pool and count them towards the vote

### Actual behavior
Smart pool tokens aren't visible to the `balance` strategy, and users dont have any voting weight.

### Steps to reproduce the behavior

This is the JSON config I'm using for MetaFactory's snapshot config (https://snapshot.page/#/metafactory.eth/settings)

Link to the pool:  https://pools.balancer.exchange/#/pool/0x3c035c3f8e271e12df1bed648024e60249f507c3/

```json
{
  "symbol": "GEAR",
  "address": "0xfb5453340c03db5ade474b27e68b6a9c6b2823eb",
  "decimals": 18
}
```

Looking into the strategy, I can see that the Subgraph for Balancer doesn't list poolShares for the smart pools I have liquidity in: 
image

Is there an updated subgraph that works with smart pools?

### PR DESCRIPTION
**Pull request by kibagateaux**
Fixes #115  .

Changes proposed in this pull request:
- Uses shares in a Balancer Smart Pool to track ownership of a governance token held in pool
- Requires 3 addresses - ERC20 token address representing shares in pool, contract address of smart pool to check total governance token holdings, ERC20 governance token address to check in smart pool
- Ran `npm run test --strategy-balancer-smart-pool` and results looked correct. We will be using this at MetaFactory and we are fine testing in prod

### CODE REVIEW

**Review by bonustrack — APPROVED** [review]
Looks good!

File: src/strategies/balancer-smart-pool/index.ts [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+    poolQueryParams.pools.__args.block = { number: snapshot };
+  }
+
+  const result = await subgraphRequest(
+    BALANCER_SUBGRAPH_URL[network],
+    poolQueryParams
+  );
+  if(!result || !result.pools) return {}
+  
+  const totalScore = Object.values(score).reduce((a, b) => a + b, 0);
```
Comment (hammadj) [inline src/strategies/balancer-smart-pool/index.ts:57]: Instead of calculating the total amount of GEAR like this, you'll have to fetch the total GEAR that exists directly from the ERC20 contract or an erc20 subgraph.
