### PR TITLE
fix: check for invalid arguments in `getVp`

### LINKED ISSUE #925: fix: add more validations rules to `getVp`

### PR DESCRIPTION
**Pull request by wa0x6e**
## 🧿 Current issues / What's wrong ?

From https://github.com/orgs/snapshot-labs/projects/12/views/7?pane=issue&itemId=43073796

The `getVp` passes the arguments as is to score-api without check. There are some basic check possible from the SDK, to filter out invalid requests, and lighten the score-api server load.

This will also avoid log pollution on score-api, making the log more relevant

## 💊 Fixes / Solution

Fix #925 

Add some basic argument validation on the SDK side, and return a meaningful error when argument are not valid.

## 🚧 Changes

- Add check that voter address is not empty, or `0x0000000000000000000000000000000000000000`
- Add check that network is not empty, and valid (referenced in networks.json)
- Check that the given `snapshot` is in the network range (should be greater than the network's `start` block)
- Check that `network` in strategies are valid
- Fully tests `getVp`

## 🛠️ Tests

- Send some request to `getVp` functions, with invalid data
- The function should throw an error with an error message

### CODE REVIEW

File: src/utils.ts [hunk 1]
```diff
@@ -497,6 +519,21 @@ export function getNumberWithOrdinal(n) {
...
+}
+
+function isValidAddress(address: string) {
+  return isAddress(address) && address !== EMPTY_ADDRESS;
+}
+
+function isValidSnapshot(snapshot: number | string, network: string) {
+  return (
+    (typeof snapshot === 'number' && snapshot >= networks[network].start) ||
+    snapshot === 'latest'
```
Comment (ChaituVR) [inline src/utils.ts:533]:
```suggestion
    snapshot === 'latest' ||
    (typeof snapshot === 'number' && snapshot >= networks[network].start)
```

File: src/utils.ts [hunk 2]
```diff
@@ -267,6 +268,27 @@ export async function getVp(
...
+      if (strategy.network && !isValidNetwork(strategy.network)) {
+        throw new Error(`Invalid network (${strategy.network}) in strategy`);
+      }
+    });
+  } catch (e) {
+    return Promise.reject(e);
+  }
+  if (!isValidSnapshot(snapshot, network)) {
+    return Promise.reject(
+      `Snapshot (${snapshot}) must be greater than network start block (${networks[network].start})`
```
Comment (ChaituVR) [inline src/utils.ts:288]:
```suggestion
      `Snapshot (${snapshot}) must be 'latest' or greater than network start block (${networks[network].start})`
```

File: src/utils.spec.js [hunk 3]
```diff
@@ -0,0 +1,164 @@
...
+          { voter: 'test-address' },
+          /invalid voter address/i
+        ],
+        ['voter is empty', { voter: '' }, /invalid voter address/i],
+        ['network is not valid', { network: 'mainnet' }, /invalid network/i],
+        ['network is empty', { network: '' }, /invalid network/i],
+        [
+          'snapshot is smaller than start block',
+          { snapshot: 1234 },
+          /snapshot \([0-9]+\) must be greater than network start block/i
```
Comment (ChaituVR) [inline src/utils.spec.js:67]:
```suggestion
          /snapshot \([0-9]+\) must be 'latest' or greater than network start block/i
```

File: test/e2e/utils/getVp.spec.ts [hunk 4]
```diff
@@ -0,0 +1,60 @@
...
+              decimals: 18
+            },
+            network: '1'
+          }
+        ],
+        7929876,
+        'test.eth',
+        false
+      )
+    ).to.rejects.toHaveProperty('code');
```
Comment (ChaituVR) [inline test/e2e/utils/getVp.spec.ts:27]: whats code here 

it fails with `AssertionError: expected 'Invalid network: 1319' to have property "code"`

**Review by ChaituVR — APPROVED** [review]
tAck
